dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

documentation:
  - changed-files:
      - any-glob-to-any-file: '*.md'

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - 'eslint.config.js'
          - '.prettierrc.json'
          - '.licensed.yml'
          - 'tsconfig.json'
          - 'vitest.config.ts'
